Workflow work.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,7 +1,7 @@
 name: Publish to PyPi
 
 on:
-  workflow_call:
+  workflow_dispatch:
     inputs:
       repository:
         description: Repository to publish to
@@ -16,6 +16,7 @@ on:
 jobs:
   publish-to-repo:
     name: Publish to repo
+    environment: Publishing
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -26,18 +27,22 @@ jobs:
           python-version:  ${{ inputs.python-version }}
       - name: Install poetry
         run: python -m pip install --upgrade pip poetry poetry-plugin-export
-      - name: Setup virtual environment (and project dependencies)
-        run: poetry install
-      - name: Calculate credentials
-        id: set-creds
+      - name: Configure poetry repositories
         run: |
-          case "${{ inputs.repository }}" in
-            pypi)
-              echo "TOKEN=${{ secrets.PYPI_PROD_TOKEN }}" >> $GITHUB_ENV
-              ;;
+          case "${{ inputs.repository }}"
             testpypi)
-              echo "TOKEN=${{ secrets.PYPI_TEST_TOKEN }}" >> $GITHUB_ENV
+              poetry config repositories.testpypi https://test.pypi.org/legacy/
+              poetry config http-basic.testpypi __token__ "${{ secrets.PYPI_TEST_TOKEN }}"
+              ;;
+            pypi)
+              poetry config http-basic.pypi __token__ "${{ secrets.PYPI_PROD_TOKEN }}"
+              ;;
+            *)
+              echo "Invalid repository requested: ${{ inputs.repository }}"
+              exit 1
               ;;
           esac
+      - name: Setup virtual environment (and project dependencies)
+        run: poetry install
       - name: Publish
-        run: poetry publish --build -r ${{ inputs.repository }} -u __token__ -p ${{ env.TOKEN }} --dry-run
+        run: poetry publish --build -r ${{ inputs.repository }} --dry-run
